### First test

< {%
  client.log("Hello from request script!!!")
%}

GET https://httpbin.org/status/200
User-Agent: HTTP-Client

> {%
  client.test("Request #1 is 200", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

### Check response status and content-type
GET https://httpbin.org/get

> {%
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });

  client.test("Response content-type is json", function() {
    var type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
  });
%}

### Failed again - check response status is 200
GET https://httpbin.org/status/404

> {%
  client.test("Request #3 is 200", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}
